language: python

python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - sudo apt-get -qq update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Install packages
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install matplotlib
  - pip install coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=tstoolbox --cover-branches --cover-erase

after_success:
  - coveralls
