- name: Delete workflow runs
  uses: dmvict/clean-workflow-runs@v1.0.0
  with:
    token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
    repo: user/repo
    branch: master
    run_conclusions: |
      failure
      timed_out
    save_period: 30
    save_min_runs_number: 2
